apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo-servicemonitor
  namespace: podinfo
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: podinfo
  namespaceSelector:
    matchNames:
      - podinfo
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
