grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(http_addr)s:%(http_port)s/grafana/" # the "/" at the end is important
      serve_from_sub_path: true
      enforce_domain: false
    metrics:
      enabled: true
